### ISSUE TITLE
Request: Import and Export

### ISSUE THREAD

**Issue by metroszn** [FrachlitzStudio/GUI-Webhook-Embed-Sender#1]
Hello!

Would it be possible to add the ability to Import and Export complete templates.

For example a user would be able to save not only Webhook settings **but also** Sender, Colour, Description and Content etc.

The user can create templates for each different channel they may have, export and then be able to import easily for the next time they need to use them.

Great work so far with this project! 🥇

**Comment by FrachlitzStudio** [comment]
A good idea. I will try to implement it in the near future.

**Comment by FrachlitzStudio** [comment]
Updated to **0.5.1** with this feature added.
